name: Build release packages

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          { name: K4Prox_linux_amd64, platform: linux/amd64, os: ubuntu-latest },
          { name: K4Prox_windows_amd64.exe, platform: windows/amd64, os: windows-latest },
          { name: K4Prox, platform: darwin/universal, os: macos-latest }
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Wails Build Action
      uses: dsieradzki/wails-build-action@main
      with:
        build-name: ${{ matrix.build.name }}
        build-platform: ${{ matrix.build.platform }}
        go-version: 1.18.3
        windows-nsis-installer: false
        macos-package-type: dmg
        macos-package-file-name: K4Prox_macos_universal
