name: Create release

on:
  workflow_dispatch:

jobs:
  release-version-and-build-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          git-message: 'chore(release): {version}'
          version-file: './web/src-web/package.json'
          git-user-email: damian.sieradzki@hotmail.com

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          name: ${{ steps.changelog.outputs.tag }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}